### PR TITLE
use release build

### PR DESCRIPTION
**Pull request by alexpilot11**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alexpilot11** [comment]
@conda-forge-admin, please rerender

**Comment by alexpilot11** [comment]
looks like windows isn't using the OSO_ENV=RELEASE var

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
> looks like windows isn't using the OSO_ENV=RELEASE var
>
>
Try

set OSO_ENV=RELEASE

On its own line above the build command

**Pull request merged**
