### PR TITLE
oso 0.26.3

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Notes:
- cleans up unneeded jinja vars that were confusing the bot

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
This will likely need some patches.

**Comment by alexpilot11** [comment]
`ERROR: No matching distribution found for cffi~=1.15`

can we not just lock it down to 1.15?

**Comment by bollwyvl** [comment]
can't be calling `pip install`

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Pull request merged**
